"""
Django settings for vidly project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
# from decouple import config

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wtuu^=_1uslkxhc&d)(v17ekh7@go(m@a##7t0pbg9e!0z9b9s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','.vercel.app','.now.sh']

# '.vercel.app'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'movies.apps.MoviesConfig',
    'api.apps.ApiConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vidly.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vidly.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'DATABASE_PUBLIC_URL': 'postgresql://postgres:bPJBRzLZNsrjoZsLbmwTDQxCJbldhpCG@junction.proxy.rlwy.net:33229/railway',
#         'DATABASE_URL': 'postgresql://postgres:bPJBRzLZNsrjoZsLbmwTDQxCJbldhpCG@postgres.railway.internal:5432/railway',
#         'PGDATA': '/var/lib/postgresql/data/pgdata',
#         'PGDATABASE': 'railway',
#         'PGPASSWORD': 'bPJBRzLZNsrjoZsLbmwTDQxCJbldhpCG',
#         'POSTGRES_USER': 'postgres',
#         'POSTGRES_DB': 'railway',
#         'PGUSER': 'postgres',
#         'POSTGRES_PASSWORD': 'bPJBRzLZNsrjoZsLbmwTDQxCJbldhpCG',
#         'PGHOST': 'postgres.railway.internal',
#         'PGPORT': '5432',
#         'SSL_CERT_DAYS': '820'
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'DATABASE_PUBLIC_URL': 'postgresql://postgres:bPJBRzLZNsrjoZsLbmwTDQxCJbldhpCG@junction.proxy.rlwy.net:33229/railway',
#         'DATABASE_URL': 'postgresql://postgres:bPJBRzLZNsrjoZsLbmwTDQxCJbldhpCG@postgres.railway.internal:5432/railway',
#         'PGDATA': '/var/lib/postgresql/data/pgdata',
#         'PGDATABASE': 'railway',
#         'PGPASSWORD': 'bPJBRzLZNsrjoZsLbmwTDQxCJbldhpCG',
#         'POSTGRES_USER': 'postgres',
#         'POSTGRES_DB': 'railway',
#         'PGUSER': 'postgres',
#         'POSTGRES_PASSWORD': 'bPJBRzLZNsrjoZsLbmwTDQxCJbldhpCG',
#         'PGHOST': 'postgres.railway.internal',
#         'PGPORT': '5432',
#         'SSL_CERT_DAYS': '820'
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': config('DB_NAME'),
#         'USER': config('DB_USER'),
#         'PASSWORD': config('DB_PASSWORD'),
#         'HOST': config('DB_HOST'),
#         'PORT': config('DB_PORT'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.ratujpagziidknckwqup',
        'PASSWORD': 'w_NKhyRca5Nvz8m' ,
        'HOST': 'aws-0-ap-southeast-1.pooler.supabase.com',
        'PORT': '6543'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
